data_path: /home/nate/data/DTU
output_path: /mnt/Drive1/Results/DTU/MVSNet/
device: cuda:0
seed: 43
num_workers: 12

camera:
    height: 1200
    width: 1600
    near: 425
    far: 937
    crop_h: 48
    crop_w: 64
    baseline_mode: min

inference:
    ckpt_file: pretrained_models/MVSNet/DTU/model.pt
    depth_planes: 256
    frame_spacing: 1
    num_frame: 5
    sample_mode: cluster
    scale: 1.0
    visualize: True
    vis_freq: 1

model:
  feature_channels: 32

point_cloud:
  image_region_th: 2
  depth_region_th: 2
  pix_th: 0.50
  prob_th: 0.85
  num_consistent: 3
  mask_th: 20
  max_dist: 0.5
  min_dist: 0.0
  min_point_dist: 0.03 # use 0.2 (0.03) with sparse (dense) GT point clouds
  resolution: dense # OPTIONS: [sparse, dense]

training:
    batch_size: 2
    ckpt_file:
    depth_planes: 256
    epochs: 30
    frame_spacing: 1
    grad_clip: 10.0
    learning_rate: 0.001
    lr_steps: 10,12,14
    lr_gamma: 0.50
    max_training_samples: 5000
    max_val_samples: 1000
    mvs_ckpt_freq: 1
    num_frame: 3
    random_crop: False
    sample_mode: cluster
    scale: 0.5
    visualize: True
    vis_freq: 100

visualization:
    max_depth_error: 8.0
